### PR TITLE
Add black and flake8

### PR DESCRIPTION
**Pull request by tianyizheng02**
See [this comment thread](https://github.com/pittcsc/PittAPI/pull/170#discussion_r1611872951) in #170 for more details

Add black to pre-commit and GitHub actions for automatic code formatting. Also update black to the latest version, as the old version was breaking due to an ImportError.

Add flake8 to pre-commit and Pipfile dependencies for automatic linting beyond GitHub actions.

### CODE REVIEW

**Comment by tianyizheng02** [comment]
```sh
python -m pip install --upgrade pip
pip install flake8 pytest
pip install -r requirements.txt
```
@nij-patel We're still using pip and requirements.txt in our GitHub Actions workflows when we've already transitioned to using pipenv and Pipfile for our dependencies. Is it OK to update the GitHub workflows to use pipenv as well?

**Comment by tianyizheng02** [comment]
black fails as expected, since I haven't yet run black on the codebase. I'll keep the flake8 step of the workflows as is, but I don't think they should just let those 97 warnings pass. We can leave that for possible future work.

**Comment by tianyizheng02** [comment]
Codebase passes pre-commit and GitHub Actions workflows with flake8 and black enabled

For future reference, note that flake8 is currently only configured to check for syntax errors and undefined names, which is far too narrow. This will need to be broadened to check for more errors (e.g., unused imports and common antipatterns).

**Comment by tianyizheng02** [comment]
@RitwikGupta?

**Review by RitwikGupta — APPROVED** [review]

**Pull request merged**
