### PR TITLE
Fix DiningAPI encode/decode functions

### PR DESCRIPTION
**Pull request by Rahi374**
Currently I have tests for half of the CourseAPI and half of the DiningAPI and a bunch of skeletal test functions.

Also what did we conclude regarding when no courses are offered?

### CODE REVIEW

**Comment by RitwikGupta** [comment]
We changed the project to be in modules now, so there is no more `CourseAPI`

**Comment by Rahi374** [comment]
Oh right forgot to fix that.

**Comment by azharichenko** [comment]
@Rahi374 In issue #22 I think the idea is when there are no courses offered it just returns an empty list.

**Comment by RitwikGupta** [comment]
We've actually progressed past this PR now

**Pull request closed without merging**
