### PR TITLE
Add Rate My Professors API for accessing professor ratings

### PR DESCRIPTION
**Pull request by Richie78321**
Created a new script `ratemyprofessors.py` for accessing Rate My Professors data via their exposed Apache Solr endpoint.

There is currently support for:
* Querying for professors by name (also including a [fuzzy option](https://lucene.apache.org/solr/guide/6_6/the-standard-query-parser.html#TheStandardQueryParser-FuzzySearches) that uses a more expensive but error-tolerant string edit distance algorithm).
* Querying for professors by ID.
* Making a custom Apache Solr query.

Definitely a lot of room for expansion and improvement here, and I am open to suggestions on both fronts!

Also, feel free to share opinions/concerns as to whether this belongs in the Pitt API. My perspective is that it is data that is relevant to Pitt students (in fact this was built to supply the Pitt CS Wiki with data), and therefore it should be accessible to Pitt students.

### CODE REVIEW

**Comment by Richie78321** [comment]
Any takers @azharichenko

**Comment by azharichenko** [comment]
👍🏻

**Comment by azharichenko** [comment]
I'm going to be reverting for reasoning I gave a while ago. ratemyprofessor is one of those things that should be installed separately because it applies much greater than just Pitt meaning it's a layer of complexity that we don't really wanna support (honestly this code could be used to make a really nice and simple rmp scraper). A good question is how is this different from `sports` API which uses ESPN to gather that data. The answer would be there was no immediate API from Pitt to get this information that applies directly to the university and is fairly simple in complexity. Unlike, RMP which is more subjective information about professors and is data that Pitt doesn't/should have.

**Comment by varughese** [comment]
What about an addons folder or something in the Pitt API? It's still data related to Pitt

**Comment by azharichenko** [comment]
I'd think it would be more generally beneficial if @Richie78321 just made another repo and got his code in there (with a few modifications to reduce pitt stuff) and push up his own package for rmp scraping. I'd be down to have this under PittCSC, it's just I don't think it quite fits with PittAPI

**Comment by Richie78321** [comment]
Yeah that's reasonable. For now I'll just keep it in my fork but as the wiki's scraping needs grow I'll likely throw it into its own repo

**Pull request merged**
