### PR TITLE
got people data, up to 10 people for now

### PR DESCRIPTION
**Pull request by dzheng256**
@RitwikGupta i'll figure out how to get more ok

### CODE REVIEW

**Comment by brlodi** [comment]
@dzheng256 Is there a reason you closed this without it being reviewed and accepted?

**Comment by dzheng256** [comment]
@brlodi yeah idk, i messed up. I submitted the same PR with more updates so it's fine

**Comment by brlodi** [comment]
@dzheng256 no worries just wanted to make sure!

Also just so you know, pull requests aren't static, so if you add more commits to the pulled branch they are automatically included. It makes it easy to tweak things 😃

**Comment by dzheng256** [comment]
@brlodi thanks! yeah, realized that today haha

**Pull request closed without merging**
